# Generated by Django 4.0.2 on 2022-05-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Reference',
            fields=[
                ('ReferenceID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ReferenceGroup', models.CharField(max_length=100)),
                ('ReferenceCode', models.CharField(max_length=20)),
                ('ReferenceShortDescription', models.CharField(max_length=100)),
                ('ReferenceLongDescription', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('ReferenceGroupCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('ReferenceSequence', models.IntegerField(blank=True, default=None, null=True)),
                ('ReferenceTableStatusID', models.BigIntegerField()),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('AddedByUserID', models.BigIntegerField()),
                ('UpdatedByUserID', models.BigIntegerField(blank=True, null=True)),
                ('DateUpdated', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
