# Generated by Django 4.0.2 on 2022-05-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_reference',
            options={'verbose_name': 'Refence'},
        ),
        migrations.CreateModel(
            name='M_Groups',
            fields=[
                ('GroupID', models.BigIntegerField(primary_key=True, serialize=False)),
                ('GroupName', models.CharField(max_length=100)),
                ('GroupCode', models.CharField(max_length=30)),
                ('DateAdded', models.DateTimeField(auto_now_add=True)),
                ('AddedByUserID', models.BigIntegerField()),
                ('UpdatedByUserID', models.BigIntegerField(blank=True, null=True)),
                ('DateUpdated', models.DateTimeField(blank=True, default=None, null=True)),
                ('ReferenceTableStatusID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.m_reference')),
            ],
            options={
                'verbose_name': 'Group',
            },
        ),
    ]
