# Generated by Django 4.0.2 on 2022-05-05 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_alter_m_reference_options_m_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='m_reference',
            options={'verbose_name': 'Reference'},
        ),
    ]
